Repository the-tcpdump-group/tcpdump, pull requests merged in 2019-05, with the labels that each got.

#755 Fix duplicate IP protocol printing
  print-ip-demux.c
  tests/esp1.out
  tests/esp2.out
  tests/esp5.out
Labels: improvement, text-output-fix

#723 Add dissector for SSH version exchange
  CMakeLists.txt
  Makefile.in
  netdissect.h
  print-ssh.c
  print-tcp.c
  tcp.h
  tests/TESTLIST
  tests/geneve-tcp.out
  tests/geneve-vni.out
  tests/geneve-vv.out
  tests/ipoib-e.out
  tests/ipoib.out
  tests/kday4.out
  tests/kday7.out
  tests/mptcp.out
  tests/ssh.out
  tests/ssh.pcap
  win32/prj/WinDump.dsp
  win32/prj/WinDump.vcproj
Labels: improvement

#753 Factor BGP NLRI printing into a reusable function
  print-bgp.c
Labels: improvement

#668 New Ethertype protocol for Arista: Arista Vendor Specific Protocol
  CHANGES
  CMakeLists.txt
  CREDITS
  Makefile.in
  ethertype.h
  netdissect.h
  print-arista.c
  print-ether.c
  tests/TESTLIST
  tests/arista_ether-e.out
  tests/arista_ether-ev.out
  tests/arista_ether.out
  tests/arista_ether.pcap
  win32/prj/GNUmakefile
Labels: reviewed_needswork
